Lab5: Sources/main.cpp File Reference
main.cpp File Reference
#include <math.h>
#include "system.h"
#include "derivative.h"
#include "hardware.h"
#include "i2c.h"
#include "mma845x.h"
#include "delay.h"
#include "mcpio.h"
Functions
int randomWalk ()
Provides an offset value that may vary by up to +/- 1 on each call.
void report (MMA845x &accelerometer)
Report accelerometer values.
int main ()
Variables
I2c0 i2c0
MMA845x accelerometer (i2c0, MMA845x::AccelerometerMode_2Gmode)
Detailed Description
Demonstrates use of MMA845x Accelerometer over I2C
Definition in file main.cpp.
Function Documentation
main()
int main ()
Definition at line 73 of file main.cpp.
References accelerometer, USBDM::MMA845x::calibrateAccelerometer(), randomWalk(), USBDM::MMA845x::readAccelerometerXYZ(), USBDM::MMA845x::readID(), report(), SetOutput(), USBDM::waitMS(), and WritePin().
randomWalk()
int randomWalk ()
Provides an offset value that may vary by up to +/- 1 on each call.
Returns
offset value in range [MIN_OFFSET .. MAX_OFFSET]
Definition at line 40 of file main.cpp.
Referenced by main().
report()
void report (MMA845x & accelerometer)
Report accelerometer values.
Parameters
[in] accelerometer Accelerometer to use
Definition at line 61 of file main.cpp.
References USBDM::MMA845x::readAccelerometerXYZ().
Referenced by main().
Variable Documentation
accelerometer
MMA845x accelerometer(i2c0, MMA845x::AccelerometerMode_2Gmode)
Referenced by main().
i2c0
I2c0 i2c0
Definition at line 25 of file main.cpp.